### ISSUE TITLE
Still having build problem with version 3.0.0 

### ISSUE THREAD

**Issue by higorlapacw** [andyduke/styled_text_package#33] opened 2021-05-21 12:33 UTC
The closed issues #32 #31 are still happing in pub.dev 3.0.0 version.

```
7:7: Error: The non-abstract class 'CustomStyle' is missing implementations for these members:
 - TextStyle.overflow
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class CustomStyle with Diagnosticable implements TextStyle {
      ^^^^^^^^^^^
```

**Comment by andyduke** [comment] 2021-05-21 12:55
@higorlapacw Please show the output of the command `flutter doctor -v`

**Comment by higorlapacw** [comment] 2021-05-21 13:11
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E266 darwin-x64, locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)
```

**Comment by andyduke** [comment] 2021-05-21 18:05
@higorlapacw I have not been able to reproduce this problem, please provide a minimum code that reproduces this problem.

**Comment by aprimault** [comment] 2021-05-23 17:04
I have the same issue with the example code. 

Launching lib/main.dart on iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: PLHZFY3YJD
Running Xcode build...
Xcode build done.                                           16.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/styled_text-3.0.0/lib/custom_style.dart:8:7: Error: The non-abstract class 'CustomStyle' is missing implementations for these members:
     - TextStyle.overflow
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

```
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on macOS 11.3 20E232 darwin-x64, locale en-FR)
    • Flutter version 2.3.0-0.1.pre at /Users/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d72bfb8d07 (4 weeks ago), 2021-04-26 06:05:55 -0700
    • Engine revision de6e1adf97
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/local/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/local/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/local/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Users/local/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Users/local/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.7142.45/IntelliJ IDEA.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] Connected device (3 available)
    • iPad (mobile)   • 00008027-001448E62E40402E • ios            • iOS 14.4.2
    • macOS (desktop) • macos                     • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 90.0.4430.212

```

```dart
Widget rightPage = Container(
        child: Padding(
          padding: EdgeInsets.all(50.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              LimitedBox(
                child: StyledText(
                  text: 'Test: <bold>bold</bold> text.',
                  tags: {
                    'bold': StyledTextTag(style: TextStyle(fontWeight: FontWeight.bold)),
                  },
                )
              ),
            ],
          ),
        ));

**Comment by andyduke** [comment] 2021-05-24 08:03
@aprimault Do you have the same problem in the stable version of Flutter 2.2.0?

**Comment by andyduke** [comment] 2021-05-24 08:09
@higorlapacw @aprimault According to [documentation](https://api.flutter.dev/flutter/painting/TextStyle-class.html) and [source code](https://github.com/flutter/flutter/blob/b22742018b/packages/flutter/lib/src/painting/text_style.dart#L452) of stable Flutter version there is no `overflow` property in the `TextStyle` class. It is only available in the [**master channel**](https://github.com/flutter/flutter/blob/c3e1d75ce0ca3f68157b92a43826f2649b015dbc/packages/flutter/lib/src/painting/text_style.dart#L799). Use the stable version of Flutter, by the time the next stable version of Flutter is released - I will add support for all changes.

**Comment by higorlapacw** [comment] 2021-05-24 10:30
Hi, @andyduke, as my flutter doctor answer shows, I am in the stable channel. I will try to get more info about this issue. 

> Channel stable

**Comment by andyduke** [comment] 2021-05-26 00:41
@higorlapacw Please show the output of the extended "flutter doctor **-v**" command.

**Comment by standup2go** [comment] 2021-05-31 04:44
I've got the same issue (Flutter 2.2.1)

`[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.2.1 at C:\DevCenter\flutter
    • Framework revision 02c026b03c (3 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\VuQuangHoa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: E:\\DevCenter\\Android\\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at E:\\DevCenter\\Android\\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = E:\\DevCenter\\Android\\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Redmi Note 8 (mobile) • 2f5bba55 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)            • edge     • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!`

-----
`Launching lib\main.dart on Redmi Note 8 in debug mode...
/C:/DevCenter/flutter/.pub-cache/hosted/pub.dartlang.org/styled_text-1.0.3+3/lib/custom_style.dart:6:7: Error: The non-abstract class 'CustomStyle' is missing implementations for these members:
 - TextStyle.leadingDistribution
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class CustomStyle with Diagnosticable implements TextStyle {
      ^^^^^^^^^^^
`

**Comment by brunoPetrim** [comment] 2021-05-31 11:20
This error disturbed me for a few days, so I decided to fork it to solve this problem with the new version of the flutter:
styled_text:
     git:
       url: https://github.com/brunoPetrim/styled_text_package.git
       ref: master
       path: styled_text

**Comment by higorlapacw** [comment] 2021-05-31 11:45
@brunoPetrim, could you consider opening a PR, please?

**Comment by andyduke** [comment] 2021-05-31 11:48
@brunoPetrim @higorlapacw I do not add support for this property until a stable version of Flutter is released with this property, so as not to break compatibility with the current stable version of Flutter.

**Comment by rmtmckenzie** [comment] 2021-06-02 19:15
@andyduke Some people have to live on the dev/master/etc branches for other reasons. If @brunoPetrim would consider doing a PR, would you consider releasing the fix as a preview version (https://dart.dev/tools/pub/publishing#publishing-previews)?

That way when it hits stable, the preview version will automatically become the release version.

**Comment by deepak786** [comment] 2021-06-23 10:09
I also forked the repo and solved the issue for dev channel:

```
styled_text:
    git:
      url: https://github.com/deepak786/styled_text_package
      path: styled_text
```

But the better solution will be to delete the style classes such as `custom_style.dart` as it is already deprecated.

**Comment by rodion-m** [comment] 2021-07-04 17:56
@andyduke  Thanks for a great library, but now it's not working in beta channel too.

**Comment by andyduke** [comment] 2021-07-04 22:42
@rodion-m The package only works with the stable version of Flutter. For the beta channel, use the forks given in the comments above.

**Comment by rodion-m** [comment] 2021-07-04 22:45
> @rodion-m The package only works with the stable version of Flutter. For the beta channel, use the forks given in the comments above.

Yes, but perhaps it costs to create a pre-release of this package to pub for beta and dev channel?

**Comment by andyduke** [comment] 2021-07-04 22:47
@rodion-m I can't do two different pre-releases for the dev and beta channels.

**Comment by deepak786** [comment] 2021-08-13 13:21
@andyduke then please remove the class`custom_style.dart`.
This class is deprecated already in the package and this is the class that is conflicting between stable and other flutter channels.

**Comment by andyduke** [comment] 2021-08-13 16:34
@deepak786 I am not removing this class yet, because it is possible that not all users have switched to the new version of the StyledText package yet.

**Comment by deepak786** [comment] 2021-08-13 16:43
So then they can use the older version of styled_package.

**Comment by DenisGL** [comment] 2021-09-08 19:58
Hello,
I have the same error:
```
Error: The non-abstract class 'CustomStyle' is missing implementations for these members:
 - TextStyle.overflow
```
after upgrading to Flutter 2.5 stable version.

With styled_text 3.0.1 and 3.0.2

**Comment by andyduke** [comment] 2021-09-09 14:43
@DenisGL @deepak786 @rmtmckenzie @rodion-m In the next few days, I will update StyledText to be compatible with Flutter 2.5.

**Comment by andyduke** [comment] 2021-09-13 15:29
A new version of StyledText 3.0.3 (compatible with Flutter 2.5) is already available on pub.dev.

**Closed as completed by andyduke** 2021-09-13 15:29 UTC

**Comment by DenisGL** [comment] 2021-09-13 16:12
Thanks a lot!
