### ISSUE TITLE
Consectuive interpreted tags within a String that are space-separated will lose the space

### ISSUE THREAD

**Issue by Zabadam** [andyduke/styled_text_package#19] opened 2021-01-21 20:47 UTC
# Example
I have a `description` property that is a passed to a `StyledText()` widget. 

One such `description` reads: 
"A finely crafted hat adorned with an inky black strand of `<link npc='crow'>`Crow`</link>` `<link id='feather'>`feather`</link>`. Well-suited for the hero that strikes from afar."

When rendered in my application, the String has lost the space between the consectuive `<link>` tags, resulting in: 
"A finely crafted hat adorned with an inky black strand of __Crowfeather__. Well-suited for the hero that strikes from afar."

**Comment by Zabadam** [comment] 2021-01-22 01:59
As a workaround I have added a `.replaceAll('&s;', ' ')` check to `e.value`;
employed in .JSON database thusly: 
"A finely crafted hat adorned with an inky black strand of `<link npc='crow'>`Crow`</link>`&s;`<link id='feather'>`feather`</link>`. Well-suited for the hero that strikes from afar." (no space between consecutive tags, only '&s;')

When rendered in my application, the String has an appropriate space between the consectuive <link> tags because there is a third recognized symbol between them injecting it; resulting in:
"A finely crafted hat adorned with an inky black strand of **Crow feather**. Well-suited for the hero that strikes from afar."

**Comment by andyduke** [comment] 2021-01-22 17:13
@Zabadam At the moment the problem is in the [xmlstream](https://github.com/jorishermans/xmlstream) package which I am using to parse tags. I created a [issue](https://github.com/jorishermans/xmlstream/issues/12) in the package's github, but temporarily as a workaround you can use `&space;` between tags: `<b>bold</b>&space;<i>italic</i>`

**Comment by andyduke** [comment] 2021-01-24 14:09
@Zabadam A issue was fixed in xmlstream, I released a new version where the problem was fixed.

**Closed as completed by andyduke** 2021-01-24 14:09 UTC
